vscode:
  extensions:
    - alexkrechik.cucumberautocomplete
    - codezombiech.gitignore
    - redhat.java
    - vscjava.vscode-java-pack
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - anwar.papyrus-pdf