name: RestAssured maven CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Set up JDK
        uses: actions/setup-java@v2
       with:
           java-version: '11'
           java-package: jdk
           architecture: x64
           check-latest: false
           server-id: github
           server-username: GITHUB_ACTOR
           server-password: ${{ secrets.GITHUB_TOKEN }}
           overwrite-settings: true
           job-status: success

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Set up Maven
        run: |
          echo ${{ secrets.ACCESS_TOKEN }} > ~/.m2/settings.xml
          mvn --version

      - name: Build and Test
        run: mvn clean install

